# Generated by Django 5.1.4 on 2024-12-19 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('smpt_server', models.CharField(max_length=255)),
                ('smpt_email', models.CharField(max_length=255)),
                ('smpt_password', models.CharField(max_length=32)),
                ('smpt_port', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='images/')),
                ('aboutus', models.TextField(max_length=255)),
                ('contact', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject_tutor', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
